[package]
name = "eddy-ts"
version = "0.1.0"
edition = "2018"
authors = ["Brian Vincent <brainn@gmail.com>"]
homepage = "https://github.com/bvinc/eddy"
license = "MIT"

[build-dependencies]
cc="*"

[dependencies]
tree-sitter = "0.17"