[package]
name = "eddy-workspace"
version = "0.1.0"
edition = "2018"
authors = ["Brian Vincent <brainn@gmail.com>"]
homepage = "https://github.com/bvinc/eddy"
license = "MIT"

[dependencies]
log = "0.4"
ropey = "1.2"
unicode-segmentation = "1.3"
eddy-ts = {path = "../eddy-ts"}
eddy-highlight = {path = "../eddy-highlight"}
serde = "1.0"
toml = "0.5"