[package]
authors = ["Brian Vincent <brainn@gmail.com>"]
categories = ["editor"]
description = "eddy text editor"
edition = "2018"
homepage = "https://github.com/bvinc/eddy"
keywords = ["eddy"]
license = "MIT"
name = "eddy"
repository = "https://github.com/bvinc/eddy"
version = "0.2.0"

[dependencies]
anyhow = "1.0"
cairo-rs = "0.15"
eddy-workspace = {path = "../eddy-workspace"}
env_logger = "0.9"
gio = "0.15"
gobject-sys = "0.15"
graphene-rs = "0.15"
gtk = {package = "gtk4", version = "0.4"}
gtk-macros = "0.3"
lazy_static = "1.0"
libc = "0.2"
log = "0.4"
lru-cache = "0.1"
once_cell = "1.3"
pango = "0.15"
pangocairo = "0.15"
ropey = "1.2"
serde_json = "1.0"
servo-fontconfig = "0.5"
syntect = "4.2"
