[package]
authors = ["Brian Vincent <brainn@gmail.com>"]
categories = ["editor"]
description = "eddy text editor"
edition = "2021"
homepage = "https://github.com/bvinc/eddy"
keywords = ["eddy"]
license = "MIT"
name = "eddy"
repository = "https://github.com/bvinc/eddy"
version = "0.2.0"

[dependencies]
anyhow = "1.0"
cairo-rs = "0.17"
eddy-workspace = {path = "../eddy-workspace"}
env_logger = "0.10"
gio = "0.17"
gobject-sys = "0.17"
gtk = {package = "gtk4", version = "0.6"}
gtk-macros = "0.3"
lazy_static = "1.0"
libc = "0.2"
log = "0.4"
lru-cache = "0.1"
once_cell = "1.3"
pango = "0.17"
pangocairo = "0.17"
ropey = "1.5"
serde_json = "1.0"
servo-fontconfig = "0.5"
