[package]
name = "eddy"
version = "0.2.0"
edition = "2018"
authors = ["Brian Vincent <brainn@gmail.com>"]
homepage = "https://github.com/bvinc/eddy"
description = "eddy text editor"
repository = "https://github.com/bvinc/eddy"
keywords = ["eddy"]
categories = ["editor"]
license = "MIT"

[dependencies]
anyhow = "1.0"
cairo-rs = {git = "https://github.com/gtk-rs/gtk-rs-core"}
env_logger = "0.9"
eddy-workspace = { path = "../eddy-workspace"}
gio = {git = "https://github.com/gtk-rs/gtk-rs-core"}
# glib = {git = "https://github.com/gtk-rs/gtk-rs-core"}
# glib-sys = {git = "https://github.com/gtk-rs/gtk-rs-core"}
gobject-sys = {git = "https://github.com/gtk-rs/gtk-rs-core"}
graphene-rs = {git = "https://github.com/gtk-rs/gtk-rs-core"}
gtk = {package="gtk4", git = "https://github.com/gtk-rs/gtk4-rs"}
gtk-macros = "0.3"
lazy_static = "1.0"
libc = "0.2"
log = "0.4"
lru-cache = "0.1"
once_cell = "1.3"
pango = {git = "https://github.com/gtk-rs/gtk-rs-core"}
pangocairo = {git = "https://github.com/gtk-rs/gtk-rs-core"}
ropey = "1.2"
serde_json = "1.0"
servo-fontconfig = "0.5"
syntect = "4.2"
