[package]
name = "eddy"
version = "0.2.0"
edition = "2018"
authors = ["Brian Vincent <brainn@gmail.com>"]
homepage = "https://github.com/bvinc/eddy"
description = "GTK frontend, written in Rust, for the xi editor"
repository = "https://github.com/bvinc/eddy"
keywords = ["eddy", "xi"]
categories = ["editor"]
license = "MIT"

[dependencies]
anyhow = "1.0"
cairo-rs = "0.9"
env_logger = "0.8"
eddy-workspace = { path = "../eddy-workspace"}
gdk = "0.13"
gio = "0.9"
glib = "0.10"
glib-sys = { version = "0.10", features = ["v2_44"] }
gobject-sys = "0.10"
gtk = { version = "0.9", features = ["v3_18"] }
gtk-sys = { version = "0.10", features = ["v3_18"] }
lazy_static = "1.0"
libc = "0.2"
log = "0.4"
once_cell = "1.3"
pango = { version = "0.9", features = ["v1_38"] }
pangocairo = "0.10"
relm = "0.20"
relm-derive = "0.20"
ropey = "1.2"
serde_json = "1.0"
servo-fontconfig = "0.5"
syntect = "4.2"